// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGFsjkMyMiNUFITHqcEopLNPfaqJ--pNk',
    appId: '1:922833932086:web:66ca24452c3776d9cfed97',
    messagingSenderId: '922833932086',
    projectId: 'mental-coach-c7f94',
    authDomain: 'mental-coach-c7f94.firebaseapp.com',
    storageBucket: 'mental-coach-c7f94.firebasestorage.app',
    measurementId: 'G-Q3Q73TFEHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJWawjlgAJgnY3EUpzyYONRz_xcBIFwfU',
    appId: '1:922833932086:android:f5757fc95b74ca60cfed97',
    messagingSenderId: '922833932086',
    projectId: 'mental-coach-c7f94',
    storageBucket: 'mental-coach-c7f94.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTJf_lELv7xccJ2s-kZKPjg7Io8wgCUlM',
    appId: '1:922833932086:ios:dd5ab62a07086606cfed97',
    messagingSenderId: '922833932086',
    projectId: 'mental-coach-c7f94',
    storageBucket: 'mental-coach-c7f94.firebasestorage.app',
    androidClientId:
        '922833932086-01its621967iqie5arkfuso31b705dpd.apps.googleusercontent.com',
    iosClientId:
        '922833932086-6c678rfhovn21taj03o1nda58lt8d787.apps.googleusercontent.com',
    iosBundleId: 'com.eitanazaria.mentalcoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTJf_lELv7xccJ2s-kZKPjg7Io8wgCUlM',
    appId: '1:922833932086:ios:0f89d2a48facd198cfed97',
    messagingSenderId: '922833932086',
    projectId: 'mental-coach-c7f94',
    storageBucket: 'mental-coach-c7f94.firebasestorage.app',
    androidClientId:
        '922833932086-fhg20ipk095ud13t3d39h52tq978se7a.apps.googleusercontent.com',
    iosClientId:
        '922833932086-dgpfa67pv7pgrviaba65iii2jqd063pj.apps.googleusercontent.com',
    iosBundleId: 'com.example.mentalCoachFlutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGFsjkMyMiNUFITHqcEopLNPfaqJ--pNk',
    appId: '1:922833932086:web:d56513eff6fb92a8cfed97',
    messagingSenderId: '922833932086',
    projectId: 'mental-coach-c7f94',
    authDomain: 'mental-coach-c7f94.firebaseapp.com',
    storageBucket: 'mental-coach-c7f94.firebasestorage.app',
    measurementId: 'G-WYP0ZZY69T',
  );
}
