[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/api/health"
port = 3000
timeout = 30

[[services]]
name = "mental-coach-api"
type = "web"

[[services.ports]]
port = 3000
targetPort = 3000