[build]
builder = "dockerfile"
dockerfilePath = "./Dockerfile"
buildCommand = "docker build --build-arg VITE_API_URL=$VITE_API_URL --build-arg VITE_ENV=$VITE_ENV ."

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/health"
port = 80
timeout = 30

[[services]]
name = "mental-coach-admin"
type = "web"

[[services.ports]]
port = 80
targetPort = 80